AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Get:
    Type: AWS::Serverless::Function
    Properties:
      Handler: HelloWorld::HelloWorld.Bootstrap::ExecuteFunction
      Runtime: dotnetcore2.1
      CodeUri: HelloWorld.zip
      MemorySize: 512
      Timeout: 30
      Role: null
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: GET
Outputs:
  ApiURL:
    Description: API endpoint URL for Prod environment
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
